apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analytics.tasks.federatednode.com
spec:
  group: tasks.federatednode.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
                - user
                - project
                - source
              properties:
                image:
                  type: string
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                    idpId:
                      type: string
                project:
                  type: string
                pr_num:
                  type: string
                dataset:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                env:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                outputs:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                inputs:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                source:
                  type: object
                  nullable: true
                  required:
                    - repository
                  properties:
                    branch:
                      type: string
                    repository:
                      type: string
                db_query:
                  type: object
                  properties:
                    query:
                      type: string
                    dialect:
                      type: string
                results:
                  type: object
                  properties:
                    git:
                      type: object
                      nullable: true
                      required:
                        - repository
                      allOf:
                        - not:
                            required:
                              - other
                      properties:
                        branch:
                          type: string
                        repository:
                          type: string
                    other:
                      type: object
                      nullable: true
                      properties:
                          url:
                            type: string
                          auth_type:
                            type: string
                      oneOf:
                      - required:
                          - url
                          - auth_type
                        oneOf:
                          - not:
                              required:
                                - git
                        properties:
                          url:
                          auth_type:
                            enum:
                              - Bearer
                              - Basic
                              - AzCopy

  scope: Cluster
  names:
    plural: analytics
    singular: analytic
    kind: Analytics
    shortNames:
    - at
