apiVersion: v1
kind: Secret
metadata:
  name: controller-user-creds
  namespace: {{ .Values.namespaces.controller }}
data:
  SYS_USER_PASS: {{ randAlphaNum 24 | b64enc | quote }}
  SYS_USER_EMAIL: {{ print "controller@fn.com" | b64enc }}
